apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
       - image: postgres
         name: postgres
         env:
         - name: POSTGRES_USER
           value: matthias
         - name: POSTGRES_PASSWORD
           value: password
         - name: POSTGRES_DB
           value: mydb
         ports:
         - containerPort: 5432
           name: postgres
         volumeMounts:
           - name: data
             mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
  selector:
    app: postgres
