apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todobackend
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: todobackend
      labels:
        app: todobackend
    spec:
      containers:
      - name: todobackend
        image: maeddes/todobackend:v1
---
apiVersion: v1
kind: Service
metadata:
  name: todobackend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: todobackend        