apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todobackend
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: todobackend
      labels:
        app: todobackend
    spec:
      containers:
        env:
        - name: BUILD_NUMBER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres.build.number
        - name: todobackend
          image: mirna/todobackend:v$BUILD_NUMBER
---
apiVersion: v1
kind: Service
metadata:
  name: todobackend
spec:
  type: LoadBalancer
  ports:
  - port: 8082
  selector:
    app: todobackend        
